Repository Kernstall/Exadel-ats, pull requests merged in 2018-07, with the labels that each got.

#3 Edit config
  .gitignore
  package.json
Labels: good first issue, help wanted

#26 Tab component
  package.json
  src/App.js
  src/Components/TabComponent/CenteredTabs.js
  src/Components/TabComponent/ContentContainer.js
  src/Components/TabComponent/TabComponent.js
  src/Components/TabComponent/style.css
Labels: work in progress

#38 Redux
  .eslintrc.json
  src/actions/Actions.js
  src/constants/ActionTypes.js
  src/reducers/SingleReducer.js
Labels: work in progress

#161 Teacher create group component
  src/App.js
  src/actions/index.js
  src/actions/teacherCreateGroup.js
  src/commands/activities.js
  src/commands/teacherCreateGroups.js
  src/common/teacherAddGroup/DragAndDropStudents.jsx
  src/common/teacherAddGroup/FilterFieldsCard.jsx
  src/common/teacherAddGroup/TeacherAddGroup.jsx
  src/common/teacherAddGroup/styles.css
  src/pages/adminMainPage/AdminMainPage.jsx
  src/pages/teacherMainPage/groupsList/GroupsList.jsx
  src/pages/teacherMainPage/teacherGroupComponent/TeacherGroupComponent.jsx
  src/reducers/index.js
  src/reducers/teacherCreateGroup.js
Labels: work in progress

#170 Teacher main page
  src/App.js
  src/pages/teacherMainPage/TeacherMainPage.jsx
  src/pages/teacherMainPage/groupTemplate/GroupTemplate.jsx
  src/pages/teacherMainPage/groupsList/GroupsList.jsx
  src/pages/teacherMainPage/studentTemplate/StudentTemplate.jsx
  src/pages/teacherMainPage/teacherGroupComponent/TeacherGroupComponent.jsx
  src/pages/teacherMainPage/teacherSelectedGroupComponent/TeacherSelectedGroupComponent.jsx
Labels: enhancement

#179 Error window
  src/App.js
  src/actions/errorMessage.js
  src/actions/index.js
  src/commands/errorMessage.js
  src/common/shared/ErrorDispatcher/ErrorDispatcher.jsx
  src/common/shared/ErrorDispatcher/ErrorWindow.jsx
  src/common/teacherAddGroup/FilterFieldsCard.jsx
  src/reducers/errorMessage.js
  src/reducers/index.js
Labels: work in progress

#160 demo logic created. wip
  package.json
  src/App.js
  src/actions/index.js
  src/actions/userLogin.js
  src/commands/userLogin.js
  src/common/api/index.js
  src/common/loginForm/LoginForm.jsx
  src/common/loginForm/PrivateRouter.js
  src/common/loginForm/api/index.js
  src/common/teacherQuestionList/TeacherQuestionList.jsx
  src/common/teacherTasksList/TeacherTasksList.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/studentMainPage/StudentMainPage.jsx
  src/pages/teacherMainPage/TeacherMainPage.jsx
  src/pages/teacherMainPage/groupsList/GroupsList.jsx
  src/reducers/index.js
  src/reducers/userLogin.js
Labels: good first issue
